name: Run
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: NDK
        run: echo $ANDROID_NDK_HOME
      - name: NDK
        run: echo $ANDROID_NDK
      - name: Download File
        run: wget https://free.keep.sh/5IuhtpSaMHcNpm6l/audio.tar.gz/download -O audio.tar.gz
      - name: Extract
        run: tar -xf audio.tar.gz
      - name: build
        run: |
           rustup target add aarch64-linux-android
           cd audio && make libextention_arm64-v8a
 
