name: Build
on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Pass the file'
        required: true
jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - name: Print the file info
        run: file ${{ inputs.data }}
